<a href="https://colab.research.google.com/github/rameshpolaveni2576/python-basics-assignment/blob/main/pandas_session2_practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [26]:
desired_filter=titanic[["survived","sex","age","fare","class"]]
desired_filter1=desired_filter[(desired_filter["sex"]=="female")&(desired_filter["class"]=="First")&(desired_filter["survived"]==1)]

     survived     sex   age      fare  class
1           1  female  38.0   71.2833  First
3           1  female  35.0   53.1000  First
11          1  female  58.0   26.5500  First
31          1  female   NaN  146.5208  First
52          1  female  49.0   76.7292  First
..        ...     ...   ...       ...    ...
856         1  female  45.0  164.8667  First
862         1  female  48.0   25.9292  First
871         1  female  47.0   52.5542  First
879         1  female  56.0   83.1583  First
887         1  female  19.0   30.0000  First

[91 rows x 5 columns]

In [28]:
desired_filter1=desired_filter1.sort_values(["fare"],ascending=True)
desired_filter1

     survived     sex   age      fare  class
862         1  female  48.0   25.9292  First
796         1  female  49.0   25.9292  First
136         1  female  19.0   26.2833  First
11          1  female  58.0   26.5500  First
194         1  female  44.0   27.7208  First
..        ...     ...   ...       ...    ...
742         1  female  21.0  262.3750  First
311         1  female  18.0  262.3750  First
88          1  female  23.0  263.0000  First
341         1  female  24.0  263.0000  First
258         1  female  35.0  512.3292  First

[91 rows x 5 columns]

In [30]:
desired_filter_single_line = titanic[titanic["sex"]=="female"].loc[(titanic["class"]=="First") &
 (titanic["survived"]==1),
 ["survived","sex","age","fare","class"]].sort_values(by="fare", ascending=True)
display(desired_filter_single_line)

     survived     sex   age      fare  class
862         1  female  48.0   25.9292  First
796         1  female  49.0   25.9292  First
136         1  female  19.0   26.2833  First
11          1  female  58.0   26.5500  First
194         1  female  44.0   27.7208  First
..        ...     ...   ...       ...    ...
742         1  female  21.0  262.3750  First
311         1  female  18.0  262.3750  First
88          1  female  23.0  263.0000  First
341         1  female  24.0  263.0000  First
258         1  female  35.0  512.3292  First

[91 rows x 5 columns]

In [35]:
titanic[(titanic["sex"]=="female")&(titanic["class"]=="First") &
 (titanic["survived"]==1)][["sex","age","fare"]].sort_values("fare",ascending=True)

        sex   age      fare
862  female  48.0   25.9292
796  female  49.0   25.9292
136  female  19.0   26.2833
11   female  58.0   26.5500
194  female  44.0   27.7208
..      ...   ...       ...
742  female  21.0  262.3750
311  female  18.0  262.3750
88   female  23.0  263.0000
341  female  24.0  263.0000
258  female  35.0  512.3292

[91 rows x 3 columns]

In [5]:
sales_data = {
    "Region": ["North", "South", "North", "East", "South", "East", "North", "South", "East", "North"],
    "Product": ["A", "B", "A", "C", "B", "A", "C", "A", "B", "B"],
    "Sales": [250, 150, 300, 200, 180, 220, 190, 210, 240, 280],
    "Quantity": [5, 3, 6, 4, 3, 4, 5, 4, 5, 6]
}

df = pd.DataFrame(sales_data)
df

  Region Product  Sales  Quantity
0  North       A    250         5
1  South       B    150         3
2  North       A    300         6
3   East       C    200         4
4  South       B    180         3
5   East       A    220         4
6  North       C    190         5
7  South       A    210         4
8   East       B    240         5
9  North       B    280         6

In [10]:
df_north_sum=df[df["Region"]=="North"].sum()
print(df_north_sum)

Region      NorthNorthNorthNorth
Product                     AACB
Sales                       1020
Quantity                      22
dtype: object

In [11]:
df_north_sum=df[df["Region"]=="South"].sum()
print(df_north_sum)

Region      SouthSouthSouth
Product                 BBA
Sales                   540
Quantity                 10
dtype: object

In [12]:
df_north_sum=df[df["Region"]=="East"].sum()
print(df_north_sum)

Region      EastEastEast
Product              CAB
Sales                660
Quantity              13
dtype: object

In [15]:
df.groupby("Region")["Sales"].sum()

Region
East      660
North    1020
South     540
Name: Sales, dtype: int64

In [16]:
df.groupby("Region")["Quantity"].sum()

Region
East     13
North    22
South    10
Name: Quantity, dtype: int64