<a href="https://colab.research.google.com/github/rameshpolaveni2576/python-basics-assignment/blob/main/Practice_Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
student_data=np.array([91,84,83,97,97,92])
print(student_data)
print(np.mean(student_data))
print(np.median(student_data))
print(student_data.dtype)

[91 84 83 97 97 92]
90.66666666666667
91.5
int64

In [1]:
import pandas as pd
print(pd.__version__)

2.2.2

In [4]:
scores = pd.Series([91, 83.0, 84.0, 97.0,97,92])
print(scores)

0    91.0
1    83.0
2    84.0
3    97.0
4    97.0
5    92.0
dtype: float64

In [6]:
scores = pd.Series(
    [91, 83.0, 84.0, 97.0,97,92],
    index=["Telugu", "Hindhi", "English", "Maths","Science", "Social"]
)
print(scores["Telugu"])

91.0

In [10]:
print(scores.values)
print(scores.index)

[91. 83. 84. 97. 97. 92.]
Index(['Telugu', 'Hindhi', 'English', 'Maths', 'Science', 'Social'], dtype='object')

In [52]:
scores_dict={
    "Name":["Ramesh","Rivansh","Vrushali","Abhilash","Harthik","Anusha"],
    "Telugu":[91,84,83,56,87,92],
    "Hindhi":[84,84,83,87,97,85],
    "English":[83,84,83,97,85,81],
    "Maths":[97,84,83,97,85,85],
    "Science":[97,84,83,97,85,85],
    "Social":[92,84,83,97,95,89]
             }
df=pd.DataFrame(scores_dict)
subject_total = ["Telugu", "Hindhi", "English", "Maths", "Science", "Social"]
df["Total"] = df[subject_total].sum(axis=1)
df=pd.DataFrame(scores_dict)
print(df.shape)
print(df.columns)
df

(6, 7)
Index(['Name', 'Telugu', 'Hindhi', 'English', 'Maths', 'Science', 'Social'], dtype='object')

       Name  Telugu  Hindhi  English  Maths  Science  Social
0    Ramesh      91      84       83     97       97      92
1   Rivansh      84      84       84     84       84      84
2  Vrushali      83      83       83     83       83      83
3  Abhilash      56      87       97     97       97      97
4   Harthik      87      97       85     85       85      95
5    Anusha      92      85       81     85       85      89

In [59]:
import numpy as np
arr=np.array([[85,54,69],[45,85,89]])
df=pd.DataFrame(arr,columns=["T","H","E"])
df

    T   H   E
0  85  54  69
1  45  85  89

In [72]:
import numpy as np
st_marks=np.array([[23,85,54,69,56,56,34],[21,56,76,87,45,85,89],[25,56,76,87,45,85,89],[24,56,76,87,45,85,89],[23,56,76,87,45,85,89],[28,56,76,87,45,85,89]])
df=pd.DataFrame(st_marks,columns=["Age","T","H","E","M","SC","SO"], index=["Rams","Riv","Vru","Har","Abhi","Anu"])
print(df.dtypes)
df

Age    int64
T      int64
H      int64
E      int64
M      int64
SC     int64
SO     int64
dtype: object

      Age   T   H   E   M  SC  SO
Rams   23  85  54  69  56  56  34
Riv    21  56  76  87  45  85  89
Vru    25  56  76  87  45  85  89
Har    24  56  76  87  45  85  89
Abhi   23  56  76  87  45  85  89
Anu    28  56  76  87  45  85  89